import Head from 'next/head'
import {items} from "../constants";
import Link from "next/link";
import React from "react";
import Card from "../components/Card";
import classnames from "../styles/Home.module.css"
import {useRouter} from "next/router";

export default function Home() {

    const router = useRouter();
    return (<>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={classnames.list}>
                {items.map((item) => (<Link
                        href={`/product/${item.id}?id=${item.id}`}
                        key={item.id}
                    >
                        <Card {...item} />
                    </Link>))}
            </div>

        </>)
}
